name = "listing-mate"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]

[assets]
directory = ".open-next/assets"

