name = "listing-mate"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"] # IMPORTANT: Ensure this is also enabled in the Cloudflare Dashboard under Settings > Functions

